baseURL = 'https://tikapro.id/'
enableRobotsTXT = true
disableKinds = ['taxonomy', 'term']
defaultContentLanguage = 'id'
defaultContentLanguageInSubdir = false

[languages]
  [languages.id]
    languageCode = 'id'
    languageName = 'Bahasa'
    weight = 1
    title = 'TikaPro - Laporan Keuangan Otomatis, Rekonsiliasi Bank & Invoice Otomatis'
  [languages.en]
    languageCode = 'en'
    languageName = 'English'
    weight = 2
    title = 'TikaPro - Automated Financial Reports, Bank Reconciliation & Invoicing'

[sitemap]
  changefreq = 'monthly'
  priority = 0.5
