baseURL = 'https://tikapro.id/'
languageCode = 'id'
title = 'TikaPro - Laporan Keuangan Otomatis, Rekonsiliasi Bank & Invoice Otomatis'
enableRobotsTXT = true
disableKinds = ['taxonomy', 'term']

[sitemap]
  changefreq = 'monthly'
  priority = 0.5
